---
abstract: 'search nested hashref/arrayref structures using JSONPath'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-Path
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  JSON::Path:
    file: lib/JSON/Path.pm
    version: 0.205
  JSON::Path::Helper:
    file: lib/JSON/Path.pm
    version: 0.205
requires:
  Exporter::Tiny: 0
  JSON: 2.00
  LV: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/JSON-Path/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=JSON-Path
  homepage: https://metacpan.org/release/JSON-Path
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://github.com/tobyink/p5-json-path
version: 0.205
